### ISSUE TITLE
Update authorship and citation

### ISSUE THREAD

**Issue by jmshapir** [JMSLab/eventstudyr#20]

**Comment by nateschor** [comment]
@jmshapir @jorpppp @chansen776 @santiagohermo just checking if anyone needs any type of disclaimer (such as funding) present in the repo for their institution/bank? @SimonFreyaldenhoven is looking into it for me and him.

Thanks!

**Comment by jorpppp** [comment]
> @jmshapir @jorpppp @chansen776 @santiagohermo just checking if anyone needs any type of disclaimer (such as funding) present in the repo for their institution/bank? @SimonFreyaldenhoven is looking into it for me and him.
> 
> Thanks!

Me neither, thanks @nateschor
