### ISSUE TITLE
Initial release

### ISSUE THREAD

**Issue by santiagohermo** [JMSLab/eventstudyr#25]
This is an issue to:
1. Make a few final adjustments to the package
2. Complete an initial release of the package and test that the package works after going public

We may also discuss related topics that come up.

**Comment by SimonFreyaldenhoven** [comment]
@jmshapir @santiagohermo @nateschor  I can confirm that I was able to install from RStudio using the instructions [here](https://github.com/JMSLab/eventstudyr/tree/6e0c39801239435c66ce20148737155c2723be10#installation).

**Comment by jmshapir** [comment]
Summary: In this issue we took the package live and confirmed it can be installed using the [posted instructions](https://github.com/JMSLab/eventstudyr/tree/6e0c39801239435c66ce20148737155c2723be10#installation).

A pull request for some housekeeping on tests is in #26.

Release is [v1.0.0](https://github.com/JMSLab/eventstudyr/releases/tag/v1.0.0).

**Comment by SimonFreyaldenhoven** [comment]
@jmshapir 

Sorry, I was to quick!

It went through and installed all dependencies for me, but the package itself actually threw an error (I think it just hung for a bit before this last part and I didn't realize it wasn't finished). See below for my error:

![image](https://user-images.githubusercontent.com/20975521/226146954-b8ea82ff-1432-4230-9dd7-678e3a005a17.png)

I'm getting a similar one on two machines, so I think this might be an issue with the package rather than my machine.

**Comment by jmshapir** [comment]
@SimonFreyaldenhoven ok! We can look at this before we start on #27 #28.

**Comment by santiagohermo** [comment]
I had the same error when trying to install the package from GitHub @SimonFreyaldenhoven @jmshapir! 

Do you think it'll be possible to save the data used by the package in `csv` format instead of `RData` @nateschor? From [here](https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/save) (see argument version) it looks like the version that is supported by R changes over time.

I propose we:

1. Create a new branch
2. Implement a fix
3. Try installing from the branch to make sure the fix works
4. PR + release 1.0.1 :)

---

Btw, here is what ChatGPT thinks we should do to fix this:

<details>
  <summary>ChatGPT proposed solution</summary>

### Prompt

I am working on an R package that we recently released publicly. I tried to install it via devtools::install_github but I get the following error:

```console
Installing package into ‘C:/Users/el_he/AppData/Local/R/win-library/4.2’
(as ‘lib’ is unspecified)
* installing *source* package 'eventstudyr' ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
Warning: file 'df_EventStudyFHS_example.RData' has magic number 'versi'
  Use of save versions prior to 2 is deprecated
Error in load(zfile, envir = tmp_env) : 
  bad restore file magic number (file may be corrupted) -- no data loaded
ERROR: lazydata failed for package 'eventstudyr'
```

Do you know how I could fix this?

### Reply

It seems that the error message is caused by a corrupted dataset file (`df_EventStudyFHS_example.RData`). The error message states that the file has a "magic number" of "versi" and that the use of save versions prior to 2 is deprecated. This suggests that the file was saved in an outdated format that is no longer supported.

One way to fix this issue is to update the package by creating a new version of the dataset file (`df_EventStudyFHS_example.RData`) using a supported version of the save function. You can do this by following these steps:

1. Load the data into R using the `load()` function.
5. Save the data using the `save()` function with a version greater than or equal to 2. For example, you can use `save(..., version = 2)` to save the data in a supported format.
6. Replace the old dataset file with the new version.
7. Rebuild and reinstall the package.

Here's an example of how to update the dataset file:

```R
# Load the data
data <- readRDS("df_EventStudyFHS_example.rds")

# Save the data in a supported format
save(data, file = "df_EventStudyFHS_example.RData", version = 2)

# Replace the old dataset file with the new version
# Make sure to remove the old file first
file.remove("df_EventStudyFHS_example.RData")
file.rename("df_EventStudyFHS_example.RData", "inst/extdata/df_EventStudyFHS_example.RData")

# Rebuild and reinstall the package
devtools::document()
devtools::build()
devtools::install()
```

I hope this helps you fix the issue. Let me know if you have any further questions.


</details>

**Comment by santiagohermo** [comment]
In branch `issue25_installation`I tried to save the `.Rdata` explicitly in version 3 (as proposed by ChatGPT), but when I try to install the package from the branch with 

```R
devtools::install_github("JMSLab/eventstudyr", ref = "issue25_installation")
```

I still get the same error. 

I think it'd be good to avoid the `RData` format altogether to save data, but not sure how feasible this is. I presume that @nateschor is more familiar than me with this part of the repo.

**Comment by nateschor** [comment]
> I think it'd be good to avoid the `RData` format altogether to save data, but not sure how feasible this is. I presume that @nateschor is more familiar than me with this part of the repo.

@santiagohermo yes I agree! `.RData` leads to headaches (like this one). Hadley [suggests](https://r-pkgs.org/data.html#sec-data-data) using `.rda`, which I see you switched to in https://github.com/JMSLab/eventstudyr/commit/441dd0cd574874a80b750315201f0adc330bc2fe.

Did you create the dataset in https://github.com/JMSLab/eventstudyr/commit/441dd0cd574874a80b750315201f0adc330bc2fe using `usethis::use_data(package_data_name)`? Is it working on your end now?

-------------------------------

Possibly related, but the `.RData` file is preventing me from running `git pull` or `git stash` (I'm on main). 

@santiagohermo @rcalvo12 do you know if this could be happening because of switching to lfs in https://github.com/JMSLab/eventstudyr/commit/b5769118e499622e408c653d833f64e4323ed15a and https://github.com/JMSLab/eventstudyr/commit/bd60363f57633518e107979edb72aa5c8398d944? Any suggestions for how I can handle this `.RData` set?

Thanks!

![image](https://user-images.githubusercontent.com/70981003/226390151-e255376e-aeb7-45b4-83f7-640aea450aee.png)
![image](https://user-images.githubusercontent.com/70981003/226390175-3575c2c7-82ac-40ff-963c-fe7cce5d83fc.png)

**Comment by santiagohermo** [comment]
Thanks @nateschor! I tried a few things but still I get the same error.

```console
Warning: file 'df_EventStudyFHS_example.rda' has magic number 'versi'
  Use of save versions prior to 2 is deprecated
Error in load(zfile, envir = tmp_env) : 
  bad restore file magic number (file may be corrupted) -- no data loaded
ERROR: lazydata failed for package 'eventstudyr'
* removing 'C:/Users/el_he/AppData/Local/R/win-library/4.2/eventstudyr'
```

> Did you create the dataset in [441dd0c](https://github.com/JMSLab/eventstudyr/commit/441dd0cd574874a80b750315201f0adc330bc2fe) using `usethis::use_data(package_data_name)`? Is it working on your end now?

Yes, I created the dataset using that function first. Then, I tried doing the same and explicitly declaring the version, like this:

```R
usethis::use_data(package_data_name, version = 3, overwrite = T)
```

Nothing worked for now :/. I'll stop trying things now, let me know if you find anything!

**Comment by nateschor** [comment]
I'm happy to work on the data format issue! Would you be able to help me with my problem in https://github.com/JMSLab/eventstudyr/issues/25#issuecomment-1476466528 first, though? I'm currently trapped on `main` and can't pull in changes so I can't work on anything until I resolve it.

If you're familiar with this problem and have time today @santiagohermo maybe a quick call + screenshare would be efficient?

**Comment by nateschor** [comment]
> Have you tried [this](https://github.com/git-lfs/git-lfs/issues/1939#issuecomment-279841780)?

Thanks @santiagohermo! Just want to confirm that it's okay for me to try 
```bash
git lfs uninstall 
git reset --hard 
git lfs install && git lfs pull
```
even though I'm on `main`?

**Comment by santiagohermo** [comment]
I think so @nateschor. The scary command there would be `git reset --hard`, but my understanding is that it forgets everything in your local branch and aligns it with `main`; i.e., you are not changing the repo with it. See e.g. [here](https://stackoverflow.com/a/15432250/15344214).

It would be problematic if you had commits in your local branch that weren't pushed, for example.

**Comment by nateschor** [comment]
@santiagohermo thanks! @SimonFreyaldenhoven just helped me--instead of using `git` commands, he just suggested deleting the local version of my file and that worked!

Thanks for the suggestions @santiagohermo! I'll start working on addressing https://github.com/JMSLab/eventstudyr/issues/25#issuecomment-1476476309 now

**Comment by nateschor** [comment]
@santiagohermo should I be working on branch `issue25_initial_release` or branch `issue25_installation`? Also just double checking that it's intentional that we have 2 branches (rather than 1) for the same issue?

![image](https://user-images.githubusercontent.com/70981003/226446810-493606a2-0c10-4fde-acd3-8433d4605272.png)

**Comment by santiagohermo** [comment]
Thanks @nateschor. It is intentional that we have two branches.

- `issue25_initial_release` makes a few updates in the `tests/testthat/input` folder. It's under review in #26 
- `issue25_installation` is the branch where we will fix the installation problem. You can try a fix and then install from the branch as explained [here](https://github.com/JMSLab/eventstudyr/issues/25#issuecomment-1475313055)

**Comment by nateschor** [comment]
I'll post more information tomorrow, but @SimonFreyaldenhoven and I are able to get the package to load!

The main change we made was in https://github.com/JMSLab/eventstudyr/commit/8ea886bd21ecdc4da8c7e87a9febe6ae1705f793, see this [thread](https://github.com/braverock/FactorAnalytics/issues/47) for more details. git lfs seems to be the culprit.

@jmshapir @santiagohermo you should be all to install the package now by running:

`devtools::install_github("JMSLab/eventstudyr", ref = "issue25_installation")`

**Comment by santiagohermo** [comment]
Awesome @nateschor! I'm also able to install the package now. I'd be happy to quickly review the changes in `issue25_installation` tomorrow.

After this two branches are merged to `main` we may want to release v1.0.1.

**Comment by santiagohermo** [comment]
I did some more testing and, at least on my computer, the problem is not fully solved. Sorry to bring the bad news!

Yes, the package is installed but still the datasets are not accessible. Two examples. First, when I clicked "Run Examples" in the documentation of `EventStudy` I found this:

<img src="https://user-images.githubusercontent.com/45404755/226479206-87a65dad-b04e-4129-bde0-1c7d89c10795.png" width="600" />

Second, when trying to access the data with `data(df_sample_dynamic)` I get an error that looks like [the one we were seeing before](https://github.com/JMSLab/eventstudyr/issues/25#issuecomment-1476476309):

<img src="https://user-images.githubusercontent.com/45404755/226479547-ad682b66-b894-4c8e-8e6f-071d49a8f7ef.png" width="600" />

Curious to see if the data is working for you @nateschor.

**Comment by SimonFreyaldenhoven** [comment]
@jmshapir @santiagohermo @nateschor Given that 

1) This repo is really small, and the small example datasets (<50kb) may be the only binary files in the repo,
2) My understanding is that we couldn't submit a version to CRAN without the lazy data load anyways
3) The issue still appears to be git-lfs related 

Any objections to disabling git-lfs for this repo?

**Comment by jmshapir** [comment]
> Any objections to disabling git-lfs for this repo?

@SimonFreyaldenhoven thanks! If we want to create some localized exceptions to the repository-wide `git-lfs` policy, I think (?) we should be able to use the fact that `.gitattributes` files have a cascading structure (https://github.com/git-lfs/git-lfs/issues/1654#issuecomment-380260698). So, for example, we could set a different policy for the `/data` subfolder by adding a `.gitattributes` file in that folder and specifying the filter pattern we want. We might have to delete and recommit the relevant files to enable non-lfs tracking.

Before implementing it might be good to test on a different repository to make sure we know what behavior to expect.

**Comment by santiagohermo** [comment]
The closest I could find to our problem is [this post](https://community.rstudio.com/t/installing-a-package-that-uses-git-lfs-to-store-large-files/8915): it looks like this is an unusual problem to have.

I would be in favor of not using `git lfs` to store the data @SimonFreyaldenhoven @jmshapir @nateschor . Other packages I've looked at do not seem to do this (eg, [see ggplot2's .gitattributes](https://github.com/tidyverse/ggplot2/blob/962fb743281618da1e85f7692fbf8a0c9dcc9a38/.gitattributes))

**Comment by SimonFreyaldenhoven** [comment]
@jmshapir @santiagohermo 

Thanks! I don't feel very strongly about not using git-lfs at all a la `ggplot2`, not using it inside the `/data` subfolder, or not using it for `.dta` files. I'm cautiously optimistic either of those would do the trick. Happy to do whatever you prefer!

I didn't quite follow this comment @jmshapir:

>Before implementing it might be good to test on a different repository to make sure we know what behavior to expect.

We know what to expect in terms of 'regular' git behavior for either of the options I propose above (tracking via git-lfs, versus regular git), right? I think the issue  (e.g. the file size issue @santiagohermo points out above) only arises as part of the package install.

**Comment by santiagohermo** [comment]
In the above commits I changed gitattributes to store `rda` data without `git lfs`, and removed/added the files in the `/data/` folder. Now

```R
devtools::install_github("JMSLab/eventstudyr", ref = "issue25_installation")
```

seems to install the package correctly. I can access data and run examples without problems. FYI @jmshapir @SimonFreyaldenhoven @nateschor

**Comment by santiagohermo** [comment]
Notes: 
- I merged #26 back to `main`. We should probably mention the branch `issue25_initial_release` in the summary comment once we wrap-up this issue.
- I updated the branch `issue25_installation` from `main`

**Comment by nateschor** [comment]
> seems to install the package correctly. I can access data and run examples without problems. FYI @jmshapir @SimonFreyaldenhoven @nateschor

same here! On my end, running the code below produces the expected plot from the `EventStudyPlot` first example.



```r
devtools::install_github("JMSLab/eventstudyr", ref = "issue25_installation")
library(eventstudyr)

estimates_ols <- EventStudy(
    estimator = "OLS",
    data = df_sample_dynamic,
    outcomevar = "y_smooth_m",
    policyvar = "z",
    idvar = "id",
    timevar = "t",
    controls = "x_r",
    FE = TRUE, TFE = TRUE,
    post = 3, overidpost = 5,
    pre = 2,  overidpre = 4,
    normalize = - 3
)

plt_ols <- EventStudyPlot(estimates = estimates_ols)
plt_ols
``` 
Time to open a PR for this issue @santiagohermo @jmshapir @SimonFreyaldenhoven?

**Comment by SimonFreyaldenhoven** [comment]
@nateschor @santiagohermo 

just to confirm - the main change that helped here is that we no longer track  `.rda` files using git-lfs right? 

I think we tried a number of other things before that, so we should decide which of the other changes we want to keep. For example, did we re-enable the lazy data load? But also happy to go over those changes as part of the PR, so opening a PR and discussing there works for me!

**Comment by jmshapir** [comment]
@santiagohermo @SimonFreyaldenhoven @nateschor thanks all!

On this from https://github.com/JMSLab/eventstudyr/issues/25#issuecomment-1478068902:

> time to open a PR for this issue @santiagohermo @jmshapir @SimonFreyaldenhoven?

I'm in favor of opening a pull. Per https://github.com/JMSLab/eventstudyr/issues/25#issuecomment-1478093487 let's assign @SimonFreyaldenhoven @jmshapir as reviewers.

On this from https://github.com/JMSLab/eventstudyr/issues/25#issuecomment-1477871625:

> We know what to expect in terms of 'regular' git behavior for either of the options I propose above (tracking via git-lfs, versus regular git), right?

Yep, I just wanted to make sure we know what kind of inheritance structure `.gitattributes` files follow.


On this from https://github.com/JMSLab/eventstudyr/issues/25#issuecomment-1478006739:

> In the above commits I changed gitattributes to store `rda` data without `git lfs`, and removed/added the files in the `/data/` folder.

Great! I made one comment on a commit that we can continue discussing during the pull.

**Comment by nateschor** [comment]
> I'm in favor of opening a pull. Per [#25 (comment)](https://github.com/JMSLab/eventstudyr/issues/25#issuecomment-1478093487) let's assign @SimonFreyaldenhoven @jmshapir as reviewers.

@santiagohermo FYI I'm working on setting up the PR!

**Comment by nateschor** [comment]
Thread continues in https://github.com/JMSLab/eventstudyr/pull/29#issue-1634468057
