### ISSUE TITLE
Address feedback from CRAN

### ISSUE THREAD

**Issue by nateschor** [JMSLab/eventstudyr#33]
Based on https://github.com/JMSLab/eventstudyr/pull/32#pullrequestreview-1377856245, we'll make any changes CRAN asks for in this issue and close the issue when we are accepted to CRAN

**Comment by nateschor** [comment]
@ew487 it looks like CRAN would like the maintainer to be the person who does the submitting. Can you do the honors?

Please make sure you've pulled the most recent changes into main, and then run `devtools::submit_cran()`.

Thank you!

@jmshapir FYI

![image](https://user-images.githubusercontent.com/70981003/230976148-4f82c8fd-1778-4fe6-8d21-ac33b14544f5.png)

**Comment by ew487** [comment]
@nateschor Just to make sure, we don't want to use `devtools::release()` and do the extra checks?

<img src="https://user-images.githubusercontent.com/108754119/231530187-89161089-0b32-4890-b863-317dbf5faab9.png" width="300">

**Comment by nateschor** [comment]
@ew487 nice find! More checks sounds great! How's this for a plan:

1. Try `devtools::release(check = TRUE)` 
2. Let us know if it's flagging things that you think we should change and we'll make the changes here
3. Submit to CRAN afterwards
      * either with `release()`, or with `submit_cran()` if `release()` is giving you a hard time

Thank you!

**Comment by nateschor** [comment]
Per call: @ew487 will keep working through the suggestions from `devtools::release(check = TRUE)`, prioritizing checks that return a failure and skipping check suggestions that seem unnecessary.

**Comment by jmshapir** [comment]
@nateschor @ew487 thanks! Is it possible to post a screenshot or other copy of the checks we're talking about?

**Comment by ew487** [comment]
@jmshapir @nateschor I tried to print out a list of checks by running `usethis::use_release_issue()`, but instead it opened a new issue in github. So that it why there is an issue #34 .

**Comment by ew487** [comment]
@jmshapir Here is a screenshot of some of the checks:
![image](https://user-images.githubusercontent.com/108754119/232076412-a819885e-e888-4cf9-bb3e-05ddde54b69d.png)

**Comment by jmshapir** [comment]
> @jmshapir @nateschor I tried to print out a list of checks by running `usethis::use_release_issue()`, but instead it opened a new issue in github. So that it why there is an issue #34 .

@ew487 thanks! I removed that issue so no worries. :-)

**Comment by ew487** [comment]
![image](https://user-images.githubusercontent.com/108754119/232078986-61c7ab53-9e9f-4504-9b8c-0fe754be9454.png)

**Comment by ew487** [comment]
Link to CRAN policies: https://cran.r-project.org/web/packages/policies.html

**Comment by jmshapir** [comment]
@ew487 thanks!

I will read those policies and follow up.

@nateschor have we already run `R CMD check --as-cran`? If not could you give that a try and let us know if there are any fatal errors that would prevent submission?

**Comment by nateschor** [comment]
> @nateschor have we already run `R CMD check --as-cran`? If not could you give that a try and let us know if there are any fatal errors that would prevent submission?

@jmshapir I have not explicitly run `R CMD check --as-cran`, but based on [this](https://kbroman.org/pkg_primer/pages/check.html) (screenshotted below) and the `devtools::check()` [documentation](https://rdrr.io/cran/devtools/man/check.html) I think we have been running `R CMD check --as-cran` via `devtools::check()`.

<details><summary>Screenshot</summary>
<p>

![image](https://user-images.githubusercontent.com/70981003/232085512-4190cb90-96ff-4949-a958-1f1eedbe6abe.png)


</p>
</details> 

I tried running from the command line below but the error about not having author or maintainer indicates to me that I'm not running the command correctly because we clearly do have author and maintainer in the `DESCRIPTION` file

<details><summary>Screenshot</summary>
<p>

![image](https://user-images.githubusercontent.com/70981003/232086604-1fc4d572-6a4b-4a1c-89c7-74dc63c1f2e9.png)


</p>
</details> 

All this to say that I think we've satisfied this checking requirement from CRAN! Please let me know though if you disagree

**Comment by jmshapir** [comment]
@nateschor thanks for confirming!

@ew487 based on https://github.com/JMSLab/eventstudyr/issues/33#issuecomment-1508791957 and my reading of the policies I think you can check [these boxes](https://github.com/JMSLab/eventstudyr/issues/33#issuecomment-1508704060) and upload!

**Comment by ew487** [comment]
@jmshapir @nateschor Great! I just uploaded it.

**Comment by nateschor** [comment]
> @jmshapir @nateschor Great! I just uploaded it.

We're in the queue!

![image](https://user-images.githubusercontent.com/70981003/232126353-05d2a957-aaa8-453f-bb33-c9166c8598cb.png)

**Comment by nateschor** [comment]
@ew487 did you hear anything from CRAN?

I see our package in the archive folder [here](https://cran.r-project.org/incoming/archive/)

<details><summary>Archive screenshot</summary>
<p>

![image](https://user-images.githubusercontent.com/70981003/232512363-2ab0e71a-f9d7-45d7-a8ff-a27425d05cef.png)

</p>
</details> 

According to the [CRAN incoming dashboard](https://r-hub.github.io/cransays/articles/dashboard.html), archive means "your package has been rejected from CRAN because it did not pass checks cleanly and the problems were not likely to be false positives."

<details><summary>CRAN status definitions</summary>
<p>

![image](https://user-images.githubusercontent.com/70981003/232513016-5c0501a0-93fe-4df1-8b5f-4f48ac9b3080.png)

</p>
</details> 

fyi @jmshapir

**Comment by ew487** [comment]
@nateschor Yes, I did! Here are the things we should fix before resubmitting.

![image](https://user-images.githubusercontent.com/108754119/232517532-83af7101-570e-4b74-9a87-6c38eda5702b.png)

**Comment by jmshapir** [comment]
@ew487 thanks!

I opened branch `33-address-feedback-from-cran` for work here.

@nateschor two things:
1. Would you have bandwidth to switch from `citEntry()` to `bibentry()`?
2. Would you be able to switch the AER citation to a DOI format?

For the NBER WP I prefer not to re-post on arxiv. Once we are ready to submit I can explain this to the folks at CRAN.

**Comment by jmshapir** [comment]
@SimonFreyaldenhoven ah good point, thanks! I hadn't realized that the NBER assigns DOI links.

I revised my comment in https://github.com/JMSLab/eventstudyr/issues/33#issuecomment-1511496543.

**Comment by nateschor** [comment]
@jmshapir I can address https://github.com/JMSLab/eventstudyr/issues/33#issuecomment-1511496543 later today!

**Comment by nateschor** [comment]
@jmshapir I made the changes in https://github.com/JMSLab/eventstudyr/commit/68e179907c8255bb163c7b9639dfb4bc1785a3b2
* updated `cran-comments.md` with our resubmission information based on the suggestions [here](https://r-pkgs.org/release.html#failure-modes)
* assumed that they wanted me to add the DOI information [here](https://github.com/JMSLab/eventstudyr/blob/68e179907c8255bb163c7b9639dfb4bc1785a3b2/DESCRIPTION#L38), but please let me know if you think there is a different place I should be adding the citation information or if I've added it incorrectly

@santiagohermo can you confirm that I correctly switched to `bibentry()`? Is it as straightforward as swapping out the function without running any code or recompiling any `.md` files?

Thanks!

**Comment by santiagohermo** [comment]
Thanks @nateschor! Yes, it looks good to me. Hopefully it also looks good to CRAN :)

**Comment by jmshapir** [comment]
@ew487 can you resubmit and let us know any feedback? Thanks!

**Comment by nateschor** [comment]
@jmshapir before @ew487 resubmits can we discuss here if we need to increment the package version number?

**Comment by jmshapir** [comment]
@nateschor thanks!

> @jmshapir I'm guessing we want to leave this issue open until after we're accepted to CRAN?

Yep, or at least for the time being.

> Given that we're:
> 
> * keeping this issue open
> * adding a few, non-code commits
> 
> Do we still follow the standard PR workflow? Or should we not delete this issue branch when we squash merge?

I think we should not open a pull at the moment, and instead keep the issue and branch open pending a reply from CRAN.

> Furthermore, do we need to increment the `eventstudyr` version number before submitting? [Here](https://r-pkgs.org/release.html#failure-modes) suggests we do ("Increase the patch version of your package. Yes, this means that there might be gaps in your released version numbers. This is not a big deal."), because I can see it being confusing to CRAN that we're saying we've made changes to the package, but we're resubmitting with the same version number

I would not favor making a new github release at this time, but I would be fine incrementing the minor version in the [package itself](https://github.com/JMSLab/eventstudyr/blob/ce901f2a0cfae960519161163924fcf296dbaa35/DESCRIPTION#L3), on the #33 issue branch, if we think that is what CRAN will expect.

**Comment by nateschor** [comment]
I won't have a chance to work on this until after 2pm today, I'm not sure if it's as simple as changing the number [here](https://github.com/JMSLab/eventstudyr/blob/ce901f2a0cfae960519161163924fcf296dbaa35/DESCRIPTION#L3) or if we need to change it with a function or in other places too. Feel free to implement before then if you're able to @santiagohermo, otherwise I can do it later!

**Comment by santiagohermo** [comment]
Version number increased in https://github.com/JMSLab/eventstudyr/commit/2eb500544326ae05f71bbff7d7470a78e3a9e41d @nateschor

**Comment by nateschor** [comment]
Thanks @santiagohermo!

@ew487 at least on my end you have the green light to resubmit with the version of the package we have in #33! @jmshapir are you also okay with @ew487 submitting?

**Comment by jmshapir** [comment]
> @jmshapir are you also okay with @ew487 submitting?

Yes thanks all!

**Comment by ew487** [comment]
@jmshapir @nateschor @santiagohermo Thanks! Just resubmitted.

**Comment by jmshapir** [comment]
![image](https://user-images.githubusercontent.com/7840353/233081620-267efcdd-d2d4-49f2-a4d0-832770da9132.png)

**Comment by nateschor** [comment]
> In https://github.com/JMSLab/eventstudyr/commit/cf2365a0f5e05ac8407fd1f8ca888a48b6f3ea4e I updated the README to add the option to install from CRAN.

Thanks @santiagohermo!

Now that we've had our fun celebrating, back to work! Proposed next steps:
1. Close this issue and open a PR
2. After we've squash-merged, update the GitHub release to includes our acceptance to CRAN and the changes we made in #28 and [here](https://github.com/JMSLab/eventstudyr/issues/28#issuecomment-1502163972). I'm thinking the version number should either be `1.1.0` or `2.0.0` since we did introduce some non-backwards compatible changes by making `PrepareLeads` and `PrepareLags` internal.
3. @santiagohermo works on #31. I'll propose some things to tackle from the "Would Like" section [here](https://github.com/JMSLab/eventstudyr/issues/28#issue-1630680952) and from the [Wiki](https://github.com/JMSLab/eventstudyr/wiki/Roadmap), please jump in with suggestions @jmshapir @rcalvo12 @ew487

Thank you!

**Comment by SimonFreyaldenhoven** [comment]
@nateschor @santiagohermo @jmshapir Thanks everyone!

I took a quick look at the files that are up on CRAN now, in particular the [Reference Manual](https://cran.r-project.org/web/packages/eventstudyr/eventstudyr.pdf), and noticed a couple of things:

1) A few hyperlinks appear to be broken, e.g.:
![image](https://user-images.githubusercontent.com/20975521/233383368-9f5e9b1e-fcd0-43c3-89bf-7bcd916b9137.png)
2) Is eta really the proxy variable?
![image](https://user-images.githubusercontent.com/20975521/233383535-238234d1-d382-4203-adec-ca660cbac5f8.png)
3) Why do we need the four different datasets? For example, it looks as if `df_EventStudyFHS_example` and `df_EventStudyOLS_example` are identical, except that the FHS version has one extra variable (eta). 
Maybe we can consolidate into one df? Simialrly, is there a reason we need the other two dataframes? Right now we introduce a lot of datasets which look pretty similar before finally, on page 5, introducing the "actual package"

**Comment by jmshapir** [comment]
@nateschor @santiagohermo @SimonFreyaldenhoven thanks!

On next steps:


> 1. Close this issue and open a PR

Agreed.

> 2. After we've squash-merged, update the GitHub release to includes our acceptance to CRAN and the changes we made in [Release to CRAN #28](https://github.com/JMSLab/eventstudyr/issues/28) and [here](https://github.com/JMSLab/eventstudyr/issues/28#issuecomment-1502163972). I'm thinking the version number should either be `1.1.0` or `2.0.0` since we did introduce some non-backwards compatible changes by making `PrepareLeads` and `PrepareLags` internal.

I'd probably keep the github version as of this release at 1.0.2 to align with the CRAN version.

> 3. @santiagohermo works on [Revise functions `PrepareLeads`, `PrepareLags`, and `GetFirstDifferences` #31](https://github.com/JMSLab/eventstudyr/issues/31).

Agreed.

> I'll propose some things to tackle from the "Would Like" section [here](https://github.com/JMSLab/eventstudyr/issues/28#issue-1630680952) and from the [Wiki](https://github.com/JMSLab/eventstudyr/wiki/Roadmap), please jump in with suggestions @jmshapir @rcalvo12 @ew487

@nateschor maybe you can start by opening an issue to tackle the points in https://github.com/JMSLab/eventstudyr/issues/33#issuecomment-1516352909?

More generally, now that the package is live I'd be in favor of breaking work into small chunks when possible, just so that we can wrap up issues somewhat quickly and allow users to access a current version from `main`.

Of course we shouldn't push every new github release to CRAN, but we can push every few months or so to keep CRAN somewhat in line with github.

**Comment by nateschor** [comment]
@jmshapir thanks! I agree with everything in https://github.com/JMSLab/eventstudyr/issues/33#issuecomment-1516500861 and I'll have some time to work on these steps this afternoon

**Comment by jorpppp** [comment]
Thanks everyone for the great work! Publishing on CRAN definitely requires a lot of patience. Congrats!

@Constantino-Carreto-Romero Can you please request installation of `eventstudyr` on our server?

Should we publicize `eventstudyr` on Twitter now @jmshapir @SimonFreyaldenhoven?

**Comment by nateschor** [comment]
Thread continues in https://github.com/JMSLab/eventstudyr/pull/35#issue-1677221306

**Comment by nateschor** [comment]
## Summary

In this issue we [submitted](https://github.com/JMSLab/eventstudyr/issues/33#issuecomment-1505620815) to CRAN, were [rejected](https://github.com/JMSLab/eventstudyr/issues/33#issuecomment-1511479329), and then accepted.

Helpful links for monitoring our CRAN status were the [CRAN incoming dashboard](https://r-hub.github.io/cransays/articles/dashboard.html) and the [CRAN server](https://cran.r-project.org/incoming/).

Stable link to the issue branch [here](https://github.com/JMSLab/eventstudyr/tree/cf2365a0f5e05ac8407fd1f8ca888a48b6f3ea4e)
