### ISSUE TITLE
Improve documentation and logo

### ISSUE THREAD

**Issue by nateschor** [JMSLab/eventstudyr#36]
In this issue, we'll address the points raised in https://github.com/JMSLab/eventstudyr/issues/33#issuecomment-1516352909 regarding our [Reference Manual](https://cran.r-project.org/web/packages/eventstudyr/eventstudyr.pdf):

- [x] see if we can simplify down to a single sample dataset
  - [x] fix the hyperlink associated with [df_sample_dynamic](https://github.com/JMSLab/eventstudyr/blob/04691ee6beb5815114f0dabb285794e7291a3bf7/R/data.R#L1-L4) (Nathan)
  - [x] address question about the `eta_m` proxy variable for [FHS](https://github.com/JMSLab/eventstudyr/blob/04691ee6beb5815114f0dabb285794e7291a3bf7/R/EventStudyFHS.R#L27) 
  - [x] address questions about our exported datasets (Nathan)
- [x] improve [hex](https://github.com/JMSLab/eventstudyr/issues/28#issuecomment-1483017461)
- [x] add link in readme to CRAN-compiled vignette
- [x] add acknowledgments
- [x] clean up [Roadmap](https://github.com/JMSLab/eventstudyr/wiki/Roadmap)

We'll wait to work on this until we wrap up #35

**Comment by jmshapir** [comment]
FHS example such as here:

https://github.com/JMSLab/eventstudyr/blob/04691ee6beb5815114f0dabb285794e7291a3bf7/R/EventStudyFHS.R#L20-L28

- [ ] Drop `controls`
- [ ] Declare `proxy = x_r`

**Comment by jmshapir** [comment]
@nateschor per below we have a datastore (stored in GoogleDrive) associated with this repository.

It looks like we haven't touched it in a while.

Are we using it actively?

If not I will remove it; we can always respawn later if needed.

Thanks!

![image](https://user-images.githubusercontent.com/7840353/234108745-9e9a4312-777b-45e5-8352-c4833ab3cb04.png)

**Comment by jmshapir** [comment]
(To be clear, I will also snapshot before I remove so we can always get back to it if we need to.)

**Comment by nateschor** [comment]
> Are we using it actively?

@jmshapir we're not actively using the data in GoogleDrive, feel free to remove. Thanks!

**Comment by jmshapir** [comment]
@nateschor great, thanks.

I've made a private snapshot called `eventstudyr1_0_2.zip` and will now delete the drive.

**Comment by nateschor** [comment]
> * improve [hex](https://github.com/JMSLab/eventstudyr/issues/28#issuecomment-1483017461)

@jorpppp I'm experimenting with a bunch of combinations for hex border and interior based on the following palettes from [here](https://cran.r-project.org/web/packages/khroma/vignettes/tol.html):
* bright
* high contrast
* vibrant
* medium contrast
* pale
* light

I have a little less than 1,000 combinations (way too many to push!) and I'll quickly flip through them and select my favorite 20 or so and push them to an issue sub folder for you to take a look at. How does that sound?

Thanks!

**Comment by nateschor** [comment]
> address questions about our exported datasets

@SimonFreyaldenhoven some points about the [3 datasets](https://github.com/JMSLab/eventstudyr/tree/e430cf59ee0c2ac6adfe190c11dc6f432972d95a/data) we're thinking about not exporting. All of the places the datasets are currently used in the repo are shown in the collapsible sections. 

## df_EventStudyFHS_example.rda and df_EventStudyOLS_example.rda

We were originally going to make `EventStudyFHS()` and `EventStudyOLS()` user-facing, but decided to keep them internal in https://github.com/JMSLab/eventstudyr/issues/17#issuecomment-1448268132. Now that the functions are internal, we don't need to be concerned about referencing these two datasets in examples. However, it would still be helpful to keep the datasets internal rather than removing them entirely since some of our `OLS` and `FHS` tests rely on the datasets.

I'm in favor of making these datasets internal, so that we can still use them but they won't be included in the `eventstudyr` [manual](https://cran.r-project.org/web/packages/eventstudyr/eventstudyr.pdf) (where they take up a ton of space, as you pointed out). How does that sound? 

<details><summary>df_EventStudyFHS</summary>
<p>

![image](https://user-images.githubusercontent.com/70981003/234617945-1497763f-94ea-47d6-95e3-6122fd824ea6.png)

</p>
</details> 

<details><summary>df_EventStudyOLS</summary>
<p>

![image](https://user-images.githubusercontent.com/70981003/234618070-5292b1fb-dc1e-4b67-9bb7-219218d57dc5.png)

</p>
</details> 

## df_sample_static.rda

As of now, making this dataset internal won't work because we use it in on of our `EventStudy()` [examples](https://github.com/JMSLab/eventstudyr/blob/e430cf59ee0c2ac6adfe190c11dc6f432972d95a/R/EventStudy.R#L88-L101). Would you like us to remove the static example? Or is there a way we can use the dynamic dataset to illustrate a similar point?

<details><summary>df_sample_static</summary>
<p>

![image](https://user-images.githubusercontent.com/70981003/234618203-7732a941-58e4-447e-883f-8bcfb0642b44.png)

</p>
</details> 

Thanks!

**Comment by nateschor** [comment]
Per discussion with @SimonFreyaldenhoven we'll: 

* make `df_sample_static.rda`, `df_EventStudyFHS_example.rda`, and `df_EventStudyOLS_example.rda` internal since it would take time to rewrite the tests that depend on these datasets
* change `df_sample_dynamic.rda`'s name (`example_data`?)
* switch the variables we use in our lone [static example ](https://github.com/JMSLab/eventstudyr/blob/e430cf59ee0c2ac6adfe190c11dc6f432972d95a/R/EventStudy.R#L88-L101) to variables from `df_sample_dynamic.rda` since we can still illustrate our static model with other data

**Comment by nateschor** [comment]
@jorpppp I showed some of my favorite hexes (below) to @SimonFreyaldenhoven:

<details><summary>Hex 1</summary>
<p>

![image](https://user-images.githubusercontent.com/70981003/235186079-cf4b2252-7959-4c5a-8a21-657488148b5f.png)

</p>
</details> 

<details><summary>Hex 2</summary>
<p>

![image](https://user-images.githubusercontent.com/70981003/235186939-dfa063e5-0551-4d6f-8163-f39a9b4b96a9.png)

</p>
</details> 

<details><summary>Hex 3</summary>
<p>

![image](https://user-images.githubusercontent.com/70981003/235187028-b8810198-cd19-4ac1-8800-749171d9084d.png)

</p>
</details> 

@SimonFreyaldenhoven pointed out that red and green is not color blind friendly. Based on [this](https://davidmathlogic.com/colorblind/#%23648FFF-%23785EF0-%23DC267F-%23FE6100-%23FFB000), orange and blue should work well. @elianasena and @kobleary (also Simon's RA) suggested removing the axes labels since [most hexes](https://github.com/GuangchuangYu/hexSticker) have less going on and have a more prominent image than those above, so I tweaked the design to make the one below that I really like!

<details><summary>Hex 4</summary>
<p>

![image](https://user-images.githubusercontent.com/70981003/235187794-1930d4ae-b6fe-45d9-9925-2d4939375511.png)

</p>
</details> 

@jorpppp please let me know:
* if you prefer a hex with the axes or without the axes
* if you have color preferences for the points, hex interior, and hex border. I like having the points and hex border use the same color
* any other changes you'd lke

@jmshapir fyi

Thanks!

**Comment by SimonFreyaldenhoven** [comment]
@nateschor Just removing the hyperlinks whenever they appear in in the titles and replacing them with a plain reference sounds good to me!

**Comment by SimonFreyaldenhoven** [comment]
@nateschor Thanks! I like Hex 4!

**Comment by jorpppp** [comment]
@nateschor Thanks, hex4 looks great! Is there any chance you can put a smoothest line on hex4? I figure as it is right now, it is showing one of the features that differentiates eventstudyr from other packages (the sup-t CIs), so might as well try to show another feature.

**Comment by nateschor** [comment]
@jorpppp what do you think of this?

![hex_1002](https://user-images.githubusercontent.com/70981003/235219679-5d223ccc-df12-4a6e-8bb6-b63db809a6ca.png)

**Comment by jorpppp** [comment]
I like it! What do you think @SimonFreyaldenhoven ?

**Comment by SimonFreyaldenhoven** [comment]
@jorpppp I'm fine with either and can see an argument for both.

It's true that the smoothest line is one of the features that is novel. But people looking for a standard event-study package might find the line a bit confusing/off-putting, given it's not used widely in the literature. 

If I had to vote, I'd probably go vanilla DiD.

**Comment by nateschor** [comment]
@jorpppp @SimonFreyaldenhoven since deciding on the hex is the only [remaining task](https://github.com/JMSLab/eventstudyr/issues/36#issue-1677236734), okay for me to close this issue and continue the conversation in the PR?

**Comment by jorpppp** [comment]
Let's go with vanilla then, without the line. Thanks @nateschor @SimonFreyaldenhoven

**Comment by nateschor** [comment]
Thread continues in #37

**Comment by nateschor** [comment]
## Summary

In this issue, we adjusted the documentation in the [reference manual](https://cran.r-project.org/web/packages/eventstudyr/eventstudyr.pdf) and improved the `README`.

**Reference Manual**
* made the FHS, OLS, and static datasets internal. We are keeping them (for now) because a number of our unit tests use these datasets
* made the dynamic dataset the sole exported dataset and changed the name to `example_data`. All examples now use this dataset
* removed links to the paper in the title of functions since the links were not rendering properly 

**README**
* generated the file using `README.Rmd` so that we could easily include an example of the output from `EventStudyPlot`
* added links to the reference manual and vignette
* included badges displaying the current version on CRAN and our total number of downloads
* added an Acknowledgments section
* created a hex for the package

Stable link to branch [here](https://github.com/JMSLab/eventstudyr/tree/04ed01f43970321ab530be594f7d8c377d398404)

Stable link to issue subfolder [here](https://github.com/JMSLab/eventstudyr/tree/04ed01f43970321ab530be594f7d8c377d398404/issue36)
