### ISSUE TITLE
Release to CRAN

### ISSUE THREAD

**Issue by jmshapir** [JMSLab/eventstudyr#44]
- [x] Update version number in [DESCRIPTION](https://github.com/JMSLab/eventstudyr/blob/e0df193455bf298e6706b4d1d6575c7e6fe3fa43/DESCRIPTION) to 1.1.2
- [x] Check for [reverse dependencies](https://r-pkgs.org/release.html#sec-release-revdep-checks)
- [x] Update the [comments for CRAN](https://r-pkgs.org/release.html#sec-release-cran-comments)  
- [x] Submit to CRAN
- [ ] On CRAN acceptance, merge to `main` and update github version to harmonize with CRAN

**Comment by jmshapir** [comment]
@ew487 does the below from [here](https://cran.r-project.org/web/packages/eventstudyr/index.html) mean that the submission was successful?

If so do you want to open a pull assigned to @rcalvo12?

Thanks!


![image](https://github.com/JMSLab/eventstudyr/assets/7840353/d085433d-3c38-4148-9371-605a23e7aac6)

**Comment by ew487** [comment]
@jmshapir Yes I think so!

**Comment by ew487** [comment]
Thread continues in its pull request #45

**Comment by ew487** [comment]
**Summary**
In this issue, we updated the package to version to 1.1.2 and resubmitted to CRAN.
[Link](https://github.com/JMSLab/eventstudyr/tree/1ce4f4c672449a01401e22d2f0ead4551e41dcd1) to issue branch
Merged to main [here](https://github.com/JMSLab/eventstudyr/commit/b0d5bcdd05aa8ac56a23a06bd76c41d5e328c513)

**Comment by jmshapir** [comment]
@ew487 thanks and yep, let's make a release to harmonize the github version with the CRAN version, thanks!
