### ISSUE TITLE
Problem with unbalanced panel

### ISSUE THREAD

**Issue by yang-yuchuan** [JMSLab/eventstudyr#46]
Hi, thanks for providing this fantastic package.

I found that there exists a tiny problem if my dataset is an unbalanced panel. This error will occur in the internal function `ComputeShifts` if `timevar_holes = TRUE`, in this case lines 48-55 in `ComputeShifts` will be executed. It seems that the "policyvar_fd" variable (e.g., `z_fd` in the example data) will simultaneously exists in `df` and `df_all`, which makes `z_fd` be replaced with `z_fd.x` and `z_fd.y` in the final data after merging. Here is a replication using example data after extracting random rows to imitate the unbalanced situation.

``` r
EventStudy(
    estimator = "OLS",
    data = example_data |> dplyr::slice(-sample(1:2000, 10)), 
    outcomevar = "y_smooth_m",
    policyvar = "z",
    idvar = "id",
    timevar = "t",
    controls = "x_r",
    pre=0, post=4
)

#> Error in eval(predvars, data, env) : object 'z_fd' not found
```

I guess changing `merge(df, df_all, by = c(idvar, timevar), all.x = TRUE)` into `merge(df, df_all, by = c(idvar, timevar, shiftvar), all.x = TRUE)` in line 55 in `ComputeShifts` will be fine? 

Appreciate your help for solutions, thanks again for your hard work!

**Comment by santiagohermo** [comment]
You were precisely right in detecting the issue and suggesting a solution @yang-yuchuan, thanks for raising this! The fix to the CRAN version should be implemented in the next version of the package, and in github right after #48 is merged.

**Comment by santiagohermo** [comment]
### Summary
In this issue we fixed the code to correctly handle the case of unbalanced panels. We also added some related tests.

Changes added to master in fd4fccb

**Comment by yang-yuchuan** [comment]
Thanks @santiagohermo! The package goes well now!
