### ISSUE TITLE
Switch maintainer

### ISSUE THREAD

**Issue by jmshapir** [JMSLab/eventstudyr#47]
@ew487 can we find out the procedure to switch the identity of the [CRAN maintainer](https://github.com/JMSLab/eventstudyr/issues/33#issuecomment-1502196404) from @ew487 to @santiagohermo?

Thanks!

**Comment by ew487** [comment]
@jmshapir From these threads:

https://stat.ethz.ch/pipermail/r-package-devel/2023q2/009055.html
https://stat.ethz.ch/pipermail/r-package-devel/2021q3/007138.html

it seems like we can change the maintainer to @santiagohermo by updating the DESCRIPTION page and re-submitting to CRAN, after which I will get an email confirmation request sent to my email address as the old maintainer.

**Comment by jmshapir** [comment]
@ew487 thanks!

After @santiagohermo wraps up #48, I suggest we use this issue #47 to make a new release and submission to CRAN. As part of the submission we can switch the maintainer.

Since #48 is a backwards-compatible bugfix I think we can just increment the patch version.

@santiagohermo fyi.

**Comment by santiagohermo** [comment]
Thanks @jmshapir @ew487! After closing #46 I created a new branch here to change the maintainer. I agree with submitting to CRAN again:

- I already updated the patch version in #46.
- I started changing `cran-comments.md` in 8a70690

Could you briefly describe the steps you do to submit to CRAN @ew487?

After merging this branch I'm happy to release again.

**Comment by jmshapir** [comment]
@santiagohermo thanks! Main steps are in https://github.com/JMSLab/eventstudyr/issues/44#issue-2049265233.

It's possible (?) that if we are now listing @santiagohermo as maintainer, @santiagohermo can actually perform the submission. 

That would be ideal since it would ensure we have the right process in place for future updates.

**Comment by ew487** [comment]
@santiagohermo @jmshapir Thanks! It's my understanding as well that @santiagohermo can submit.

**Comment by jmshapir** [comment]
Thread continues in its pull request #49.

**Comment by santiagohermo** [comment]
### Summary 
In this issue we formally changed the maintainer of the package and completed a successful submission to CRAN.

New release is here.
